name: Setup Environment
description: Installs dependencies and caches Node modules & Cypress
runs:
  using: composite
  steps:
    - name: Restore node_modules cache
      id: packages-cache
      uses: actions/cache@v4
      with:
        path: |
          **/node_modules
          ~/.cache/Cypress
        key: ${{ runner.os }}-packages-with-cypress-${{ hashFiles('yarn.lock') }}

    - name: Install dependencies
      if: steps.packages-cache.outputs.cache-hit != 'true'
      run: yarn install --frozen-lockfile
      shell: bash
      working-directory: ${{ inputs.workdir }}
