name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  install-dependencies:
    name: Install dependencies
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install dependencies
        uses: ./.github/actions/install-deps

  integration:
    name: ⚙️ Integration Tests ${{ matrix.package }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        package: ${{ fromJSON('["web"]') }}
    needs:
      - install-dependencies
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install dependencies
        uses: ./.github/actions/install-deps

      - name: Cache turbo setup
        uses: actions/cache@v4
        with:
          path: .turbo
          key: ${{ runner.os }}-integration-${{ matrix.package }}-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-integration-${{ matrix.package }}

      - name: Run integration Test on fragment - ${{  matrix.package }}
        run: yarn integration --filter=./apps/${{  matrix.package }}
